name: BadMocha CFW Booter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:20210726

    steps:
    - uses: actions/checkout@v3
    
      
    - name: Build
      run: make
      
