name: BadMocha CFW Booter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm:20210622

    steps:
    - uses: actions/checkout@v3
    
    - name: Get devkitppc
      run: sudo apt-get update && sudo dkp-pacman -S devkitPPC --noconfirm && sudo apt-get -y install xxd
      
    - name: Build
      run: export DEVKITPPC=$devkitARM../devkitPPC && make
      
