name: BadMocha CFW Booter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm:20210622

    steps:
    - uses: actions/checkout@v3
    
    - name: Get devkitppc
      run: sudo apt-get update && sudo apt-get -y install xxd gcc-powerpc-linux-gnu make gcc flex binutils bison libssl-dev
      
    - name: Build
      run: export DEVKITPPC=/usr/ && make
      
