name: BadMocha CFW Booter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm:20210622

    steps:
    - uses: actions/checkout@v3
    
    - name: Get devkitppc
      run: sudo dkp-pacman -S devkitPPC --noconfirm && export devkitPPC=$(env devkitARM)../devkitPPC
      
    - name: Build
      run: make
      
